version: '3.3'
services:
  prometheus:
    image: 'prom/prometheus:v2.6.0'
    restart: always
    hostname: 'prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    volumes:
      - './srv/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml'
      - './srv/prometheus/config/prometheus-rules.yml:/etc/prometheus/prometheus.rules.yml'
    links:
      - nginx-vts-exporter
  nginx-vts-exporter:
    image: sophos/nginx-vts-exporter
    restart: always
    ports:
      - 9913:9913
    environment:
      NGINX_HOST: nginx
      NGINX_STATUS: "http://nginx/status/format/json"
    links:
      - nginx

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./index.html:/etc/nginx/html/index.html
      - ./srv/nginx/config/nginx.conf:/etc/nginx/nginx.conf

  alertmanager:
    image: prom/alertmanager:v0.15.2
    restart: always
    volumes:
      - ./srv/alertmanager/alertmanager.yml:/alertmanager.yml
    command:
      - '--config.file=/alertmanager.yml'
      - '--web.external-url=http://localhost:9093/'
    ports:
      - '9093:9093'
